local H = require("helpers")
local P = require("pjollrig")
local api = vim.api

local function type_body(lines)
  api.nvim_buf_set_lines(0, 0, -1, false, lines)
end

describe("editor + commands", function()
  local root
  before_each(function()
    H.reset()
    root = H.repo()
    vim.cmd.cd(root)
    vim.cmd.edit("a.lua")
  end)

  it(":Pjollrig add over a range; :w saves and stays, a second :w edits the same record, <S-CR> closes", function()
    vim.cmd("2,3Pjollrig add")
    local float = api.nvim_get_current_win()
    assert.are.equal("acwrite", vim.bo.buftype)
    assert(api.nvim_win_get_config(float).footer[1][1]:find("shift+enter submit", 1, true))
    type_body({ "first", "", "line" })
    vim.cmd("write")
    assert.are.equal(float, api.nvim_get_current_win())
    type_body({ "second" })
    vim.cmd("write")
    local recs = P.list()
    assert.are.equal(1, #recs)
    assert.are.same({ 2, 3, "two", "second" }, { recs[1].lnum, recs[1].end_lnum, recs[1].line, recs[1].body })
    type_body({ "third" })
    api.nvim_feedkeys(vim.keycode("<S-CR>"), "x", false)
    assert(not api.nvim_win_is_valid(float))
    assert.are.equal("third", P.list()[1].body)
    assert.are.equal(1, #H.marks())
  end)

  it("a second :w and edit both un-resolve a comment another nvim just sent (RV-m3)", function()
    local S = require("pjollrig.store")
    vim.cmd("Pjollrig add")
    type_body({ "v1" })
    vim.cmd("write")
    local id = P.list()[1].id
    S.patch(root, { { id, { resolved = true } } }) -- another nvim sent it; this nvim's mark is stale
    type_body({ "v2" })
    vim.cmd("write | close")
    assert.are.same({ false, "v2" }, { S.load(root)[id].resolved, S.load(root)[id].body })
    S.patch(root, { { id, { resolved = true } } })
    vim.cmd("Pjollrig edit") -- the stale mark is still under the cursor
    type_body({ "v3" })
    vim.cmd("write | close")
    assert.are.same({ false, "v3" }, { S.load(root)[id].resolved, S.load(root)[id].body })
  end)

  it("q discards; empty bodies are never saved", function()
    vim.cmd("Pjollrig add")
    vim.cmd("stopinsert")
    vim.cmd("write")
    type_body({ "unsaved" })
    api.nvim_feedkeys("q", "x", false)
    assert.are.equal(0, #P.list())
  end)

  it("edit / resolve / delete act on the comment under the cursor; list fills the loclist", function()
    P.add({ body = "orig" })
    vim.cmd("Pjollrig edit")
    type_body({ "changed" })
    vim.cmd("write | close")
    assert.are.equal("changed", P.list()[1].body)
    vim.cmd("Pjollrig list")
    assert.are.equal("changed", vim.fn.getloclist(vim.fn.win_getid(vim.fn.winnr("#")))[1].text)
    vim.cmd("wincmd p | Pjollrig resolve")
    assert.are.same({ 0, 0 }, { #P.list(), #H.marks() })
    vim.ui.select = function(items, _, cb)
      cb(items[1])
    end
    vim.cmd("Pjollrig delete") -- resolved comments have no mark: picked from the list
    assert.are.equal(0, #P.list({ all = true }))
  end)
end)
