local H = require("helpers")
local ctx

describe("pjollrig review completion", function()
  local saved_cwd
  before_each(function()
    ctx = H.setup()
    saved_cwd = vim.uv.cwd()
    require("pjollrig.review.complete")._reset()
  end)
  after_each(function()
    vim.cmd.cd(saved_cwd)
    require("pjollrig.review.complete")._reset()
    H.teardown(ctx)
    ctx = nil
  end)

  it("offers local and remote branches without removed feature keywords", function()
    local C = require("pjollrig.review.complete")
    local root, git = H.git_repo(ctx, { ["a.lua"] = { "return 1" } })
    git("branch", "feature")
    git("update-ref", "refs/remotes/origin/main", vim.trim(git("rev-parse", "HEAD").stdout))
    vim.cmd.cd(root)
    local items = C.candidates("", "PjollrigReview ")
    assert.are.same({ "feature", "main", "origin/main" }, items)
    assert.are.same({}, C.candidates("", "PjollrigReview pr "))
    assert.are.same({}, C.candidates("", "PjollrigReview chat "))
  end)

  it("prefix-filters candidates by arglead", function()
    local C = require("pjollrig.review.complete")
    local root, git = H.git_repo(ctx, { ["a.lua"] = { "return 1" } })
    git("update-ref", "refs/remotes/origin/main", vim.trim(git("rev-parse", "HEAD").stdout))
    vim.cmd.cd(root)
    assert.are.same({ "origin/main" }, C.candidates("or", "PjollrigReview or"))
  end)

  it("caches ref results across repeated completion", function()
    local C = require("pjollrig.review.complete")
    local root, git = H.git_repo(ctx, { ["a.lua"] = { "return 1" } })
    vim.cmd.cd(root)
    assert.are.same({ "main" }, C.candidates("", "PjollrigReview "))
    git("branch", "later")
    assert.are.same({ "main" }, C.candidates("", "PjollrigReview "))
    C._reset()
    assert.are.same({ "later", "main" }, C.candidates("", "PjollrigReview "))
  end)

  it("returns no candidates outside a repository", function()
    vim.cmd.cd(ctx.artifact_root)
    assert.are.same({}, require("pjollrig.review.complete").candidates("", "PjollrigReview "))
  end)

  it(":PjollrigReview delegates completion to the module", function()
    vim.cmd("runtime plugin/pjollrig.lua")
    local root = H.git_repo(ctx, { ["a.lua"] = { "return 1" } })
    vim.cmd.cd(root)
    assert.are.same({ "main" }, vim.fn.getcompletion("PjollrigReview m", "cmdline"))
  end)
end)
