name: docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - name: panvimdoc
        uses: kdheepak/panvimdoc@v4.0.1
        with:
          vimdoc: pjollrig
          version: "Neovim >= 0.12.0"
          demojify: true
          treesitter: true
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore(ci): auto-generate vimdoc"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
